# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Required Python version
python:
  version: 3.10
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build documentation using Sphinx
sphinx:
  configuration: docs/conf.py

# Set the build output formats
formats: all

# Optionally set the Python interpreter path (default is docs/)
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
